name: Build and Publish image to Docker Hub

on:
  push:
    branches:
        - main
    paths:
        - 'api/Dockerfile'
        - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker backend image
        run: docker build ./api/ -t nsawatz/devops-qr-code-api:latest

      - name: Build Docker frontend image
        run: docker build ./front-end-nextjs/ -t nsawatz/devops-qr-code-frontend:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u nsawatz --password-stdin

      - name: Push Docker api image to Docker Hub
        run: docker push nsawatz/devops-qr-code-api:latest

      - name: Push Docker frontend image to Docker Hub
        run: docker push nsawatz/devops-qr-code-frontend:latest